name: Run Xray Free

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup & Run Xray + Cloudflare Tunnel
        run: |
          # 1. Tải Xray-core
          wget https://github.com/XTLS/Xray-core/releases/latest/download/Xray-linux-64.zip
          unzip Xray-linux-64.zip -d xray_bin
          
          # 2. Tạo config VLESS
          mkdir -p /etc/xray
          cat << 'EOF' > /etc/xray/config.json
          {
            "log": { "loglevel": "warning" },
            "inbounds": [{
              "port": 10000,
              "protocol": "vless",
              "settings": {
                "clients": [{ "id": "4037e379-5a6a-41bf-9357-7783a0b8438d" }],
                "decryption": "none"
              },
              "streamSettings": {
                "network": "ws",
                "wsSettings": { "path": "/" }
              }
            }],
            "outbounds": [{ "protocol": "freedom" }]
          }
          EOF

          # 3. Chạy Xray ngầm
          ./xray_bin/xray run -config /etc/xray/config.json &

          # 4. Tải Cloudflare Tunnel và bắn ra public link
          curl -L --output cloudflared https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64
          chmod +x cloudflared
          ./cloudflared tunnel --url http://localhost:10000 --no-autoupdate
